// Code generated by protoc-gen-go.
// source: placedata.proto
// DO NOT EDIT!

package placedata

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Place struct {
	State            *string  `protobuf:"bytes,1,req,name=state" json:"state,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Lat              *float64 `protobuf:"fixed64,3,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,4,req,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}

func (m *Place) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Place) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Place) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

type PlaceList struct {
	Place            []*Place `protobuf:"bytes,1,rep,name=place" json:"place,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlaceList) Reset()         { *m = PlaceList{} }
func (m *PlaceList) String() string { return proto.CompactTextString(m) }
func (*PlaceList) ProtoMessage()    {}

func (m *PlaceList) GetPlace() []*Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func init() {
}
