// Code generated by protoc-gen-go.
// source: airportdata.proto
// DO NOT EDIT!

package airportdata

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Airport struct {
	State            *string  `protobuf:"bytes,1,req,name=state" json:"state,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Code             *string  `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	Lat              *float64 `protobuf:"fixed64,4,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,5,req,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Airport) Reset()         { *m = Airport{} }
func (m *Airport) String() string { return proto.CompactTextString(m) }
func (*Airport) ProtoMessage()    {}

func (m *Airport) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Airport) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Airport) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Airport) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Airport) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

type AirportList struct {
	Airport          []*Airport `protobuf:"bytes,1,rep,name=airport" json:"airport,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AirportList) Reset()         { *m = AirportList{} }
func (m *AirportList) String() string { return proto.CompactTextString(m) }
func (*AirportList) ProtoMessage()    {}

func (m *AirportList) GetAirport() []*Airport {
	if m != nil {
		return m.Airport
	}
	return nil
}

func init() {
}
